version: '3'
services:
  gui:
    image: bnhf/openvpn-admin-plus:latest
    container_name: openvpn-gui-tap
    environment:
    - OPENVPN_ADMIN_USERNAME=admin # Leave this default as-is and update on first-run
    - OPENVPN_ADMIN_PASSWORD=b3secure # Leave this default as-is and update on first-run
    - COUNTRY=${COUNTRY} # Country, Province, City, Org and OU are used by EasyRSA
    - PROVINCE=${PROVINCE} # Province or State
    - CITY=${CITY}
    - ORG=${ORG} # Organization - Use your company name here or make one up
    - EMAIL=${EMAIL}
    - OU=${OU} # Organizational Unit - Use your company department name or make one up
    - PIVPN_SERVER=${PIVPN_SERVER} # The unique name used for your server's certificate and key. Found in the /etc/openvpn/server.conf file.
    - PIVPN_CONF=${PIVPN_CONF} # Filename for your OpenVPN server configuration - usually server.conf
    - TZ=${TZ} # Your OpenVPN server's timezone
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - /etc/openvpn:/etc/openvpn
     - ./openvpn-data/db:/opt/openvpn-gui-tap/db
